# Generated by Django 4.1.7 on 2023-03-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agelimit',
            name='title',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='available',
            name='title',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='title',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='format',
            name='title',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
