# Generated by Django 4.1.7 on 2023-03-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_agelimit_title_alter_available_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agelimit',
            name='title',
            field=models.IntegerField(unique=True),
        ),
    ]
