# Generated by Django 4.1.7 on 2023-03-07 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_comics_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comics',
            name='age_limit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.agelimit'),
        ),
        migrations.AlterField(
            model_name='comics',
            name='available',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.available'),
        ),
        migrations.AlterField(
            model_name='comics',
            name='format',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.format'),
        ),
    ]
